import React, { useMemo, useState } from 'react'
import { ArrowLeft, CheckCircle2, FileUp, Gauge, ShieldCheck, Sparkles, Target, Upload, XCircle } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import Header from '../components/Header'
import { extractResumeText } from '../services/resumeParser'
import { analyzeATS } from '../services/ats'

const demoJD = `We are looking for a Software Engineer with experience in React, JavaScript, TypeScript, Node.js, REST APIs, SQL, Git, testing, responsive design, and Agile development. The role involves building scalable web applications, debugging issues, collaborating with cross-functional teams, optimizing application performance, and writing clean maintainable code.`

export default function AtsChecker() {
  const navigate = useNavigate(); const [file,setFile]=useState(null); const [resumeText,setResumeText]=useState(''); const [jobDescription,setJobDescription]=useState(''); const [analysis,setAnalysis]=useState(null); const [error,setError]=useState(''); const [loading,setLoading]=useState(false)
  const scoreLabel=useMemo(()=>{if(!analysis)return ''; if(analysis.score>=95)return '95+ target range'; if(analysis.score>=80)return 'Strong alignment'; if(analysis.score>=65)return 'Needs refinement'; return 'Needs improvement'},[analysis])
  async function onFile(e){const selected=e.target.files?.[0];if(!selected)return;setError('');setAnalysis(null);setFile(selected);setLoading(true);try{const text=await extractResumeText(selected);if(!text)throw new Error('No selectable text was found. For a scanned/image PDF, use OCR first or paste the resume text below.');setResumeText(text)}catch(err){setError(err.message||'Could not read this resume.')}finally{setLoading(false)}}
  function runAnalysis(){setError('');if(!resumeText.trim())return setError('Upload a resume or paste the resume text first.');if(!jobDescription.trim())return setError('Paste the specific job description before checking ATS alignment.');setAnalysis(analyzeATS(resumeText,jobDescription))}
  return <div className="min-h-screen bg-slate-50"><Header user={{name:'ATS Workspace'}} compact/><main className="mx-auto max-w-7xl px-5 py-8 sm:py-10">
    <button onClick={()=>navigate('/dashboard')} className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-slate-500 hover:text-slate-900"><ArrowLeft size={16}/> Back to workspace</button>
    <section className="optimizer-hero"><div><p className="section-kicker">Resume optimizer</p><h1 className="mt-2 max-w-3xl text-4xl font-black tracking-tight sm:text-5xl">Upload your resume. Match it to the role.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-600 sm:text-base">Use the exact job description you are targeting. The checker surfaces keyword gaps and practical changes so you know what to improve before applying.</p></div><div className="optimizer-badge"><ShieldCheck size={17}/><span>Explainable checks</span></div></section>
    <section className="mt-8 grid gap-6 lg:grid-cols-2">
      <div className="workspace-card"><div className="workspace-card-head"><div><p className="section-kicker">Step 01</p><h2>Upload your resume</h2><p>PDF, DOCX, or TXT. You can edit extracted text before analysis.</p></div><div className="icon-box"><FileUp size={19}/></div></div><label className="upload-zone"><Upload size={26} className="text-blue-600"/><div className="mt-3 text-sm font-black text-slate-900">{loading?'Reading resume…':file?file.name:'Drop or choose a resume file'}</div><div className="mt-1 text-xs text-slate-500">Selectable-text PDFs work best.</div><input onChange={onFile} type="file" accept=".pdf,.docx,.txt" className="hidden"/></label><label className="field-label mt-5">Resume text</label><textarea value={resumeText} onChange={e=>{setResumeText(e.target.value);setAnalysis(null)}} rows={15} placeholder="Your extracted resume text appears here. You can edit it before checking." className="textarea-modern"/></div>
      <div className="workspace-card"><div className="workspace-card-head"><div><p className="section-kicker">Step 02</p><h2>Paste the job description</h2><p>Use the specific posting, not a generic role description.</p></div><button onClick={()=>{setJobDescription(demoJD);setAnalysis(null)}} className="text-xs font-bold text-blue-600 hover:text-blue-700">Use demo</button></div><textarea value={jobDescription} onChange={e=>{setJobDescription(e.target.value);setAnalysis(null)}} rows={15} placeholder="Paste the full job description here..." className="textarea-modern mt-6"/>{error&&<div className="mt-4 flex items-start gap-2 rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700"><XCircle size={17} className="mt-0.5 shrink-0"/>{error}</div>}<button onClick={runAnalysis} className="mt-4 primary-btn w-full justify-center"><Gauge size={17}/> Check ATS alignment</button><div className="mt-4 grid gap-2 sm:grid-cols-3"><MiniCheck icon={<Target size={14}/>} text="Keywords"/><MiniCheck icon={<CheckCircle2 size={14}/>} text="Sections"/><MiniCheck icon={<Sparkles size={14}/>} text="Impact"/></div></div>
    </section>
    {analysis&&<section className="mt-8 space-y-5 pb-10">
      <div className="score-panel"><div className="flex flex-col gap-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-slate-400">ATS alignment score</p><div className="mt-1 text-6xl font-black">{analysis.score}<span className="text-lg text-slate-500">/100</span></div></div><span className="score-pill">{scoreLabel}</span></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-white/10"><div className="h-full rounded-full bg-blue-500 transition-all" style={{width:`${analysis.score}%`}}/></div><p className="mt-4 text-xs leading-5 text-slate-400">This is a heuristic alignment score based on the resume text and the job description you provided. It is not an employer's actual ATS result.</p></div>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Matched keywords" value={analysis.matched.length}/><Metric label="Missing keywords" value={analysis.missing.length}/><Metric label="Measured outcomes" value={analysis.metrics}/><Metric label="Detected sections" value={`${Object.values(analysis.sections).filter(Boolean).length}/7`}/></div>
      <div className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]"><section className="soft-card p-6"><div className="flex items-center justify-between gap-3"><div><p className="section-kicker">Keyword match</p><h2 className="mt-1 text-xl font-black">What the job description contains</h2></div><span className="text-xs font-semibold text-slate-500">Green = found · Amber = missing</span></div><div className="mt-4 flex flex-wrap gap-2">{analysis.keywords.slice(0,24).map(k=><span key={k} className={`rounded-full border px-3 py-1.5 text-xs font-semibold ${analysis.matched.includes(k)?'border-emerald-200 bg-emerald-50 text-emerald-700':'border-amber-200 bg-amber-50 text-amber-700'}`}>{k} {analysis.matched.includes(k)?'✓':'•'}</span>)}</div></section>
        <section className="soft-card p-6"><p className="section-kicker">95+ action plan</p><h2 className="mt-1 text-xl font-black">What to fix next</h2><div className="mt-4 space-y-3">{analysis.recommendations.map((r,i)=><div key={i} className="rounded-xl border border-slate-200 p-4"><div className="flex gap-3"><div className="mt-0.5 text-blue-600">{r.type==='keywords'?<Target size={17}/>:r.type==='impact'?<Sparkles size={17}/>:<CheckCircle2 size={17}/>}</div><div><p className="text-sm font-bold">{r.title}</p><p className="mt-1 text-xs leading-5 text-slate-600">{r.text}</p></div></div></div>)}</div></section>
      </div>
    </section>}
  </main></div>
}
function Metric({label,value}){return <div className="soft-card p-5"><p className="text-xs font-semibold uppercase tracking-[.12em] text-slate-400">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></div>}
function MiniCheck({icon,text}){return <div className="flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2 text-xs font-bold text-slate-600"><span className="text-blue-600">{icon}</span>{text}</div>}
