import React, { useEffect, useState } from 'react'
import { ArrowLeft, Check, ChevronDown, Download, ExternalLink, Mic, Plus, Sparkles, Trash2 } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import Header from '../components/Header'
import Field from '../components/Field'
import ResumePreview from '../components/ResumePreview'
import VoiceButton from '../components/VoiceButton'
import TemplateGallery from '../components/TemplateGallery'
import { getDemoUser, getResume, saveResume } from '../services/storage'
import { generateSummary } from '../services/gemini'
import { v4 as uuid } from 'uuid'

const tabs = ['Template','Personal Detail','Summary','Experience','Education','Skills']
const colors = ['#2563eb','#7c3aed','#059669','#db2777','#ea580c','#0f172a']

export default function Builder(){
 const {id}=useParams(); const navigate=useNavigate(); const [resume,setResume]=useState(getResume(id)); const [tab,setTab]=useState(0); const [busy,setBusy]=useState(false)
 useEffect(()=>{setResume(getResume(id))},[id])
 if(!resume) return <div className="p-10">Resume not found.</div>
 const update=(patch)=>{ const next=saveResume({...resume,...patch}); setResume(next) }
 const setPersonal=(key,val)=>update({personal:{...resume.personal,[key]:val}})
 const addExp=()=>update({experience:[...(resume.experience||[]),{id:uuid(),position:'',company:'',location:'',startDate:'',endDate:'',description:''}]})
 const updateExp=(eid,patch)=>update({experience:resume.experience.map(e=>e.id===eid?{...e,...patch}:e)})
 const removeExp=(eid)=>update({experience:resume.experience.filter(e=>e.id!==eid)})
 const addEdu=()=>update({education:[...(resume.education||[]),{id:uuid(),degree:'',school:'',location:'',startDate:'',endDate:'',grade:''}]})
 const updateEdu=(eid,patch)=>update({education:resume.education.map(e=>e.id===eid?{...e,...patch}:e)})
 const removeEdu=(eid)=>update({education:resume.education.filter(e=>e.id!==eid)})
 const addSkill=()=>update({skills:[...(resume.skills||[]),{id:uuid(),name:'',level:3}]})
 const updateSkill=(sid,patch)=>update({skills:resume.skills.map(s=>s.id===sid?{...s,...patch}:s)})
 const removeSkill=(sid)=>update({skills:resume.skills.filter(s=>s.id!==sid)})
 const aiSummary=async()=>{setBusy(true);try{const text=await generateSummary({jobTitle:resume.personal.jobTitle,experience:resume.experience,skills:resume.skills}); update({summary:text})}catch(e){alert('AI generation failed. Check the Gemini key or continue in demo mode.')}finally{setBusy(false)}}
 const download=()=>window.print()
 const share=async()=>{const url=`${location.origin}/my-resume/${resume.id}/view`; try{await navigator.clipboard.writeText(url);alert(`Share link copied:\n${url}`)}catch{prompt('Copy this share link:',url)}}
 return <div className="min-h-screen bg-slate-50"><Header user={getDemoUser()} compact/><div className="border-b bg-white no-print"><div className="mx-auto flex max-w-[1500px] items-center gap-3 px-5 py-3"><button onClick={()=>navigate('/dashboard')} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><ArrowLeft size={18}/></button><input value={resume.title} onChange={e=>update({title:e.target.value})} className="min-w-0 flex-1 rounded-lg px-2 py-2 text-sm font-semibold outline-none hover:bg-slate-50 focus:bg-slate-50"/><div className="flex items-center gap-2"><button onClick={share} className="hidden items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-semibold text-slate-700 sm:inline-flex"><ExternalLink size={15}/> Share</button><button onClick={download} className="inline-flex items-center gap-2 rounded-xl bg-slate-900 px-3 py-2 text-sm font-semibold text-white"><Download size={15}/> PDF</button></div></div></div>
 <main className="mx-auto grid max-w-[1500px] gap-6 px-5 py-6 lg:grid-cols-[minmax(430px,560px)_1fr]">
  <section className="builder-panel no-print"><div className="border-b border-slate-200 px-5 py-4"><div className="flex gap-2 overflow-x-auto">{tabs.map((t,i)=><button key={t} onClick={()=>setTab(i)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-sm font-semibold ${tab===i?'bg-slate-900 text-white':'text-slate-500 hover:bg-slate-100'}`}>{t}</button>)}</div></div><div className="p-5"><div className="mb-5 flex items-center gap-3 rounded-2xl border border-blue-100 bg-blue-50/70 px-4 py-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-white text-blue-600 shadow-sm"><Mic size={16}/></div><div className="min-w-0"><p className="text-xs font-black text-slate-900">Voice editing is on</p><p className="mt-0.5 text-[11px] leading-5 text-slate-500">Use <span className="font-bold text-blue-700">Speak</span> beside any editable field to dictate your resume.</p></div></div><div className="space-y-6">
   {tab===0 && <TemplateGallery value={resume.templateId || 'ats-classic'} onChange={templateId=>update({templateId})} /> }
   {tab===1 && <div className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="First Name" value={resume.personal.firstName} onChange={v=>setPersonal('firstName',v)}/><Field label="Last Name" value={resume.personal.lastName} onChange={v=>setPersonal('lastName',v)}/></div><Field label="Job Title" value={resume.personal.jobTitle} onChange={v=>setPersonal('jobTitle',v)} placeholder="Software Engineer"/><Field label="Email" type="email" value={resume.personal.email} onChange={v=>setPersonal('email',v)}/><div className="grid gap-4 sm:grid-cols-2"><Field label="Phone" value={resume.personal.phone} onChange={v=>setPersonal('phone',v)}/><Field label="Address" value={resume.personal.address} onChange={v=>setPersonal('address',v)}/></div><div className="grid gap-4 sm:grid-cols-2"><Field label="LinkedIn" value={resume.personal.linkedin} onChange={v=>setPersonal('linkedin',v)}/><Field label="Website / GitHub" value={resume.personal.website} onChange={v=>setPersonal('website',v)}/></div></div>}
   {tab===2 && <div><div className="flex items-center justify-between"><div><h2 className="font-bold">Professional Summary</h2><p className="mt-1 text-xs text-slate-500">Keep it concise and fact-based.</p></div><div className="flex items-center gap-2"><VoiceButton value={resume.summary} onChange={v=>update({summary:v})}/><button onClick={aiSummary} disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white disabled:opacity-60"><Sparkles size={14}/>{busy?'Generating...':'Generate with AI'}</button></div></div><textarea rows={11} value={resume.summary} onChange={e=>update({summary:e.target.value})} placeholder="Write a 3–4 sentence summary..." className="mt-4 w-full rounded-xl border border-slate-200 px-4 py-3 text-sm leading-6 outline-none focus:border-blue-500"/></div>}
   {tab===3 && <div><div className="flex items-center justify-between"><h2 className="font-bold">Experience</h2><button onClick={addExp} className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-3 py-2 text-xs font-bold text-white"><Plus size={14}/> Add</button></div><div className="mt-5 space-y-5">{resume.experience.map((e)=><div key={e.id} className="rounded-2xl border border-slate-200 p-4"><div className="grid gap-3 sm:grid-cols-2"><Field label="Position" value={e.position} onChange={v=>updateExp(e.id,{position:v})}/><Field label="Company" value={e.company} onChange={v=>updateExp(e.id,{company:v})}/><Field label="Location" value={e.location} onChange={v=>updateExp(e.id,{location:v})}/><div className="grid grid-cols-2 gap-3"><Field label="Start" value={e.startDate} onChange={v=>updateExp(e.id,{startDate:v})}/><Field label="End" value={e.endDate} onChange={v=>updateExp(e.id,{endDate:v})}/></div></div><Field label="Description" rows={6} value={e.description.replace(/<[^>]+>/g,'')} onChange={v=>updateExp(e.id,{description:v.split('\n').filter(Boolean).map(x=>`<ul><li>${x.replace(/^[-•]\s?/,'')}</li></ul>`).join('')})}/><button onClick={()=>removeExp(e.id)} className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold text-red-600"><Trash2 size={14}/> Remove</button></div>)}</div></div>}
   {tab===4 && <div><div className="flex items-center justify-between"><h2 className="font-bold">Education</h2><button onClick={addEdu} className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-3 py-2 text-xs font-bold text-white"><Plus size={14}/> Add</button></div><div className="mt-5 space-y-5">{resume.education.map((e)=><div key={e.id} className="rounded-2xl border border-slate-200 p-4"><div className="grid gap-3"><Field label="Degree" value={e.degree} onChange={v=>updateEdu(e.id,{degree:v})}/><Field label="School" value={e.school} onChange={v=>updateEdu(e.id,{school:v})}/><div className="grid gap-3 sm:grid-cols-2"><Field label="Location" value={e.location} onChange={v=>updateEdu(e.id,{location:v})}/><Field label="Grade" value={e.grade} onChange={v=>updateEdu(e.id,{grade:v})}/></div><div className="grid grid-cols-2 gap-3"><Field label="Start" value={e.startDate} onChange={v=>updateEdu(e.id,{startDate:v})}/><Field label="End" value={e.endDate} onChange={v=>updateEdu(e.id,{endDate:v})}/></div></div><button onClick={()=>removeEdu(e.id)} className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold text-red-600"><Trash2 size={14}/> Remove</button></div>)}</div></div>}
   {tab===5 && <div><div className="flex items-center justify-between"><h2 className="font-bold">Skills</h2><button onClick={addSkill} className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-3 py-2 text-xs font-bold text-white"><Plus size={14}/> Add</button></div><div className="mt-5 space-y-3">{resume.skills.map(s=><div key={s.id} className="flex items-end gap-3 rounded-2xl border border-slate-200 p-4"><div className="flex-1"><Field label="Skill" value={s.name} onChange={v=>updateSkill(s.id,{name:v})}/></div><label className="w-36"><span className="mb-1.5 block text-sm font-medium text-slate-700">Level</span><select value={s.level} onChange={e=>updateSkill(s.id,{level:Number(e.target.value)})} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="1">Basic</option><option value="2">Working</option><option value="3">Proficient</option><option value="4">Advanced</option><option value="5">Expert</option></select></label><button onClick={()=>removeSkill(s.id)} className="mb-1 rounded-lg p-2 text-red-600 hover:bg-red-50"><Trash2 size={16}/></button></div>)}</div><div className="mt-8"><p className="text-sm font-semibold text-slate-700">Theme Color</p><div className="mt-3 flex gap-2">{colors.map(c=><button key={c} onClick={()=>update({theme:c})} className="h-9 w-9 rounded-full ring-2 ring-offset-2 ring-transparent hover:ring-slate-300" style={{background:c}}>{resume.theme===c&&<Check className="mx-auto text-white" size={17}/>}</button>)}</div></div></div>}
  </div><div className="mt-7 flex justify-between border-t pt-5"><button disabled={tab===0} onClick={()=>setTab(tab-1)} className="rounded-xl border border-slate-200 px-4 py-2 text-sm font-semibold disabled:opacity-40">Back</button><button onClick={()=>setTab(Math.min(tabs.length-1,tab+1))} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">{tab===tabs.length-1?'Done':'Continue'}<ChevronDown size={15} className="-rotate-90"/></button></div></div></section>
  <section className="min-w-0"><div className="sticky-preview sticky top-24 p-4"><div className="mb-3 flex items-center justify-between no-print"><div><p className="text-sm font-black text-slate-800">Resume Preview</p><p className="mt-0.5 text-[11px] text-slate-400">Live A4 preview • changes save automatically</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-black text-emerald-700">LIVE</span></div><div className="overflow-auto rounded-xl pb-8"><ResumePreview resume={resume}/></div></div></section>
 </main></div>
}
